spring:
  datasource:
    url:  jdbc:h2:~/idus
    driver-class-name: org.h2.Driver
    username: idus
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /h2-console  # 콘솔의 경로

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
